/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cell;


import static forms.appointment.ongoing_table;
import static forms.appointment.pending_table;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jake Marson Nable
 */
public class action_ongoing extends javax.swing.JPanel {

   private static final String username = "root" ;
    private static final String password = "1234" ;
    private static final String dataconn = "jdbc:mysql://127.0.0.1:3306/workjob" ; 
    
    Connection sql = null;
    PreparedStatement pst  = null;
    ResultSet rs = null;
    int i, q, id, deleteitem;
    
  /**
     * Creates new form panelAction
     */
    public action_ongoing() {
        initComponents();
    }
 public void UpdateDb() {
 try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        sql = DriverManager.getConnection(dataconn, username, password);
        pst = sql.prepareStatement("SELECT * FROM ongoing_table");
        rs = pst.executeQuery();
        
        DefaultTableModel RecordTable = (DefaultTableModel) ongoing_table.getModel();
        RecordTable.setRowCount(0); 
        
        while (rs.next()) {
            
            Vector<Object> rowData = new Vector<>();
            rowData.add(rs.getInt("idongoing_table"));
            rowData.add(rs.getString("ongoing_checkin"));
            rowData.add(rs.getString("ongoing_time"));
            rowData.add(rs.getString("ongoing_name"));
            rowData.add(rs.getString("ongoing_sr"));
            rowData.add(rs.getString("ongoing_price"));
            rowData.add(rs.getString("ongoing_employee"));
            RecordTable.addRow(rowData); 
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
        e.printStackTrace(); 
    }
}
 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TAB_delete = new cell.actionButton();

        setBackground(new java.awt.Color(255, 255, 255));

        TAB_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-delete-24.png"))); // NOI18N
        TAB_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAB_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(TAB_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TAB_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TAB_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAB_deleteActionPerformed
        
 
   DefaultTableModel recordTable = (DefaultTableModel) ongoing_table.getModel();
int selectedRows = ongoing_table.getSelectedRow();

try {
    if (selectedRows != -1) { 
        int id = Integer.parseInt(recordTable.getValueAt(selectedRows, 0).toString());

        int deleteItem = JOptionPane.showConfirmDialog(null, "Confirm if you want to delete item", "Warning", JOptionPane.YES_NO_OPTION);
        if (deleteItem == JOptionPane.YES_OPTION) {
            
            try (Connection connection = DriverManager.getConnection(dataconn, username, password)) {
                
                String deleteQuery = "DELETE FROM ongoing_table WHERE idongoing_table = ?";
                try (PreparedStatement pst = connection.prepareStatement(deleteQuery)) {
                    pst.setInt(1, id);
                    int rowsAffected = pst.executeUpdate();
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(this, "Record deleted");
                        UpdateDb(); 
                    } else {
                        JOptionPane.showMessageDialog(this, "No record with ID " + id + " found.", "Warning", JOptionPane.WARNING_MESSAGE);
                    }
                }
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Warning", JOptionPane.WARNING_MESSAGE);
    }
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "SQL Error: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace(); 
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Invalid ID format.", "ERROR", JOptionPane.ERROR_MESSAGE);
} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
    ex.printStackTrace(); 
}



    }//GEN-LAST:event_TAB_deleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static cell.actionButton TAB_delete;
    // End of variables declaration//GEN-END:variables





}